### ISSUE TITLE
cannot configure the sdk

### ISSUE THREAD

**Issue by pmichard** [angus-ai/angus-sdk-python#7]
when running angusme on Mac or Ubuntu I get following errors:

`Traceback (most recent call last):`
`File "/usr/local/bin/angusme", line 336, in <module> main()`
`File "/usr/local/bin/angusme", line 333, in main create_configuration()`
`File "/usr/local/bin/angusme", line 229, in create_configuration (default_root))`
`UnboundLocalError: local variable 'default_root' referenced before assignment`

**Comment by ggate** [comment]
Hi pmichard,

Thank you for the bug report,
we just fixed it in the 0.0.10 release.

Regards,
Gwenn

**Comment by pmichard** [comment]
Jip it work's now. Thank's for the fast fix.

**Comment by pmichard** [comment]
Unfortunately I need some more help.
When I try to send an image I get following errors:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/angus/rest.py", line 223, in process
    resource_type=Job)
  File "/usr/local/lib/python3.5/site-packages/angus/rest.py", line 118, in create
    r = r.result()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 447, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 378, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 306, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 451, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 151, in _encode_files
    rf = RequestField(name=k, data=fp.read(),
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by pmichard** [comment]
update: when using binary mode it works.
See: https://github.com/angus-ai/angus-sdk-python/issues/5
